epochs: 200
test_steps: 4e4
repeats: 2
envs:
  - SimpleDeathmatch-v0
  - SimpleGather-v0
algorithms:
  -
    name: A3C
    type: A3C
    train_steps: 8e5
    config:
      initial_learning_rate: 2e-5
      preprocess_config: {frame_skip: 3}
      discount: 0.998
  -
    name: DQN
    type: DQN
    train_steps: 2e5
    config:
      initial_learning_rate: 2e-5
      batch_size: 32
      preprocess_config: {frame_skip: 3}
      discount: 0.998
  -
    name: Random
    type: Random
    train_steps: 0
